### ISSUE TITLE
ADD MORE PEOPLE

### ISSUE THREAD

**Issue by toby56** [tradeandmark/general#1]
# Consider Adding Other Contributers!

**Comment by platy11** [comment]
@toby56 Would you like to be added?

**Comment by toby56** [comment]
@platy11 Yes

**Comment by platy11** [comment]
@toby56 Just so I know it's you, please respond with your primary school house. If you respond correctly, I'll add you.

**Comment by toby56** [comment]
Conder

**Comment by platy11** [comment]
OK, I'll add you

**Comment by Toby56** [comment]
Lol
